import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { confirm } from "@inquirer/prompts";
import chokidar from "chokidar";
import dotenv from "dotenv";
import type { AssenvleConfig } from "./config.js";

const FIRST_LINES =
  "# Generated by assenvle.\n# Do not edit this file directly!\n";

function getEnvFilePaths(envDir: string, mode: string): string[] {
  const envDirPath = resolve(process.cwd(), envDir);
  const envFileNames = [
    ".env",
    `.env.${mode}`,
    ".env.local",
    `.env.${mode}.local`,
  ];
  return envFileNames.map((path) => resolve(envDirPath, path));
}

function parseEnvFile(filePath: string): Record<string, string> {
  const contents = readFileSync(filePath, { encoding: "utf8" });
  return dotenv.parse(contents);
}

async function shouldCreateOutput(
  outputFileName: string,
  outputFilePath: string,
): Promise<boolean> {
  if (!existsSync(outputFilePath)) return true;

  const fileContent = readFileSync(outputFilePath, { encoding: "utf8" });
  if (fileContent.startsWith(FIRST_LINES)) return true;

  return await confirm({
    message: `Existing ${outputFileName} does not seem to be generated by assenvle. Do you want to overwrite?`,
    default: false,
  });
}

export async function assenvle(
  mode: string,
  { envDir, outputFile, validateEnv }: AssenvleConfig,
) {
  let envObject = {};
  for (const filePath of getEnvFilePaths(envDir, mode)) {
    if (!existsSync(filePath)) continue;

    envObject = {
      ...envObject,
      ...parseEnvFile(filePath),
    };
  }

  validateEnv?.(envObject);

  const envContents = [
    FIRST_LINES,
    ...Object.entries(envObject).map(([key, value]) => `${key}="${value}"`),
  ];

  const outputFilePath = resolve(process.cwd(), outputFile);
  if (await shouldCreateOutput(outputFile, outputFilePath)) {
    writeFileSync(outputFilePath, envContents.join("\n"));
    console.info(`created ${outputFile}`);
  } else {
    console.error(`canceled to create ${outputFile}`);
    process.exit(1);
  }
}

export function assenvleOnChange(mode: string, config: AssenvleConfig) {
  chokidar
    .watch(getEnvFilePaths(config.envDir, mode))
    .on("change", async (path) => {
      const relativePath = path.replace(`${process.cwd()}/`, "");
      console.info(`changed ${relativePath}`);
      await assenvle(mode, config);
    });
}
